name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - 
      name: Build the Docker image
      run: docker build --platform linux/amd64 --tag obmud2/scraper:v1_amd64 .
    -
      name: Push Docker image
      run: docker push obmud2/scraper:v1_amd64
